apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: acm-cli-cert
  labels:
    component: acm-cli-downloads
  name: acm-cli-downloads
spec:
  ports:
  {{- if .Values.isOpenshift }}
    - name: https-8443
      port: 443
      protocol: TCP
      targetPort: 8443
  type: ClusterIP
  {{- else }}
    - nodePort: 30000
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: NodePort
  {{- end }}
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    component: acm-cli-downloads
