apiVersion: v1
kind: Service
metadata:
  labels:
    component: acm-cli-downloads
  name: acm-cli-downloads
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: downloads
  {{- if .Values.isOpenshift }}
  type: ClusterIP
  {{- else }}
      nodePort: 30000
  type: NodePort
  {{- end }}
  internalTrafficPolicy: Cluster
  sessionAffinity: None
  selector:
    component: acm-cli-downloads
