name: Test

on:
  push:
    branches:
      - main
      - release-[0-9]+.[0-9]+
  pull_request:
    branches:
      - main
      - release-[0-9]+.[0-9]+

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Lint
        run: |
          go mod verify
          make lint
          make fmt
          git diff --exit-code

      - name: GoSec Scan
        run: |
          make gosec-scan

      - name: Validate build data
        env:
          VERSION_REF: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}
        run: |
          ./build/validate-build-files.sh

  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7
        with:
          go-version-file: go.mod

      - name: Clear some space
        run: |
          df -h
          sudo rm -rf /usr/local/lib/android || true
          df -h

      - name: Build image
        run: |
          CONTAINER_ENGINE=docker make build-image

      - name: Test image
        run: |
          echo "::group::cleanup docker system"
          docker system df
          docker system prune --all --force --filter="label!=name=rhacm2/acm-cli-rhel9"
          echo "::endgroup::"

          make e2e-test
